### PR TITLE
add JDK 11 to the build matrix

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@vmg

**Comment by sullis** [comment]
@vmg

**Comment by sullis** [comment]
@vmg

**Comment by sullis** [comment]
LGTM @vmg

**Comment by sullis** [comment]
@vmg

**Comment by sullis** [comment]
ping @vmg

**Comment by sullis** [comment]
ping @vmg

**Comment by vmg** [comment]
So sorry about the delay on this! I somehow unsubscribed to my own repository. LGTM.

**Pull request merged**
